name: Anti-Dodo
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit
        run: curl -s https://monappligc3-65hgqkpyqul5xfemstzcgk.streamlit.app>/dev/null
